import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import { fileURLToPath, URL } from 'node:url';

/**
 * GitHub Pages serves a project site from /<repo>/, so the built asset paths
 * need that prefix. BASE_PATH is set by the deploy workflow; it stays "/" for
 * local development and for a custom domain.
 */
const base = process.env.BASE_PATH ?? '/';

/**
 * Emits the single-page fallback that GitHub Pages needs.
 *
 * Pages looks for a file at the address you asked for, so /projects/abc is a
 * 404 — it serves 404.html instead. That file records where the visitor was
 * going and hands back to index.html, which restores the address before the
 * router starts.
 *
 * It is generated rather than kept in public/ because it has to know the base
 * path, and files in public/ are copied without substitution. Guessing the
 * base at runtime is what the earlier version did, and it was wrong in two
 * ways: it mistook the first path segment of a user site for a repository
 * name, and it stored an address with the prefix already stripped, so the
 * restore landed outside the app.
 */
function spaFallback(basePath: string): Plugin {
  return {
    name: 'spa-fallback-404',
    apply: 'build',
    generateBundle() {
      this.emitFile({
        type: 'asset',
        fileName: '404.html',
        source: `<!doctype html>
<html lang="en-GB">
  <head>
    <meta charset="UTF-8" />
    <title>Loading…</title>
    <script>
      // Generated by vite.config.ts — edit it there, not here.
      (function () {
        var base = ${JSON.stringify(basePath)};
        var path = window.location.pathname + window.location.search + window.location.hash;

        try {
          // Stored whole, prefix included, so the restore cannot land outside
          // the application.
          sessionStorage.setItem('spa-redirect', path);
        } catch (e) {
          /* Storage unavailable: the visitor lands on the home route instead. */
        }

        window.location.replace(base);
      })();
    </script>
  </head>
  <body>
    <p>Loading…</p>
  </body>
</html>
`,
      });
    },
  };
}

export default defineConfig({
  base,
  plugins: [react(), tailwindcss(), spaFallback(base)],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  build: {
    outDir: 'dist',
    sourcemap: false,
    rollupOptions: {
      output: {
        // Split the two heaviest dependencies out of the main bundle so a
        // change to application code does not invalidate them in the cache.
        manualChunks: {
          supabase: ['@supabase/supabase-js'],
          react: ['react', 'react-dom', 'react-router-dom'],
        },
      },
    },
  },
});
